export const DEMO_CHURCHES = [
  { id:1, name:'Primera Iglesia Bautista de Guadalajara', denomination:'Bautista', city:'Guadalajara', state:'Jalisco', country:'México', founded_year:1887, description:'Iglesia pionera del movimiento bautista en el occidente de México, con más de 130 años de historia evangelística y servicio comunitario.', cover_image:'/images/church1.jpg' },
  { id:2, name:'Iglesia Cristiana Evangélica Monterrey', denomination:'Evangélica', city:'Monterrey', state:'Nuevo León', country:'México', founded_year:1921, description:'Congregación fundada por misioneros norteamericanos, hoy con 5 campus y más de 2,000 familias activas.', cover_image:'/images/church2.jpg' },
  { id:3, name:'Asambleas de Dios Ciudad de México', denomination:'Pentecostal', city:'Ciudad de México', state:'CDMX', country:'México', founded_year:1935, description:'Una de las primeras iglesias pentecostales en la capital, conocida por sus campañas de avivamiento histórico.', cover_image:'/images/church3.jpg' },
  { id:4, name:'Iglesia Metodista de Oaxaca', denomination:'Metodista', city:'Oaxaca', state:'Oaxaca', country:'México', founded_year:1898, description:'Fundada en la época porfiriana, preserva archivos históricos únicos del siglo XIX incluyendo diarios y fotografías originales.', cover_image:'/images/church4.jpg' },
  { id:5, name:'Centro Cristiano Nueva Vida Tijuana', denomination:'Carismática', city:'Tijuana', state:'Baja California', country:'México', founded_year:1978, description:'Iglesia de frontera con fuerte ministerio de alcance social y registro fotográfico de décadas de trabajo comunitario.', cover_image:'/images/church5.jpg' },
]
export const DEMO_EVENTS = [
  { id:1, church_id:1, church_name:'Primera Iglesia Bautista de Guadalajara', denomination:'Bautista', title:'Fundación Oficial de la Congregación', description:'Ceremonia de fundación con 45 miembros fundadores. El pastor J.C. Brown presidió el primer culto oficial en la calle Prisciliano Sánchez.', event_date:'1887-03-15', category:'Fundación' },
  { id:2, church_id:1, church_name:'Primera Iglesia Bautista de Guadalajara', denomination:'Bautista', title:'Primera Campaña de Avivamiento', description:'Campaña evangelística de 21 días que resultó en 230 conversiones. Predicó el evangelista William Thompson.', event_date:'1902-07-04', category:'Avivamiento' },
  { id:3, church_id:1, church_name:'Primera Iglesia Bautista de Guadalajara', denomination:'Bautista', title:'Construcción del Templo Principal', description:'Inauguración del edificio histórico de cantera que sigue en pie. Participaron más de 400 voluntarios.', event_date:'1915-12-01', category:'Construcción' },
  { id:4, church_id:2, church_name:'Iglesia Cristiana Evangélica Monterrey', denomination:'Evangélica', title:'Llegada de los Primeros Misioneros', description:'El matrimonio Henderson llega a Monterrey con literatura bíblica y materiales de educación cristiana.', event_date:'1921-09-10', category:'Misiones' },
  { id:5, church_id:2, church_name:'Iglesia Cristiana Evangélica Monterrey', denomination:'Evangélica', title:'Primera Conferencia Bíblica Regional', description:'Reunión histórica de 12 iglesias del noreste. Se establecieron relaciones denominacionales duraderas.', event_date:'1948-04-22', category:'Conferencia' },
  { id:6, church_id:3, church_name:'Asambleas de Dios Ciudad de México', denomination:'Pentecostal', title:'Gran Avivamiento de la Capital', description:'Culto al aire libre en el Zócalo con más de 10,000 asistentes. Reportado por varios diarios de la época.', event_date:'1952-05-20', category:'Avivamiento' },
  { id:7, church_id:4, church_name:'Iglesia Metodista de Oaxaca', denomination:'Metodista', title:'Archivo Fotográfico Digitalizado', description:'Rescate y digitalización de 1,200 fotografías del siglo XIX donadas por familias fundadoras.', event_date:'2018-11-11', category:'Patrimonio' },
  { id:8, church_id:5, church_name:'Centro Cristiano Nueva Vida Tijuana', denomination:'Carismática', title:'30 Aniversario de la Congregación', description:'Celebración con más de 3,000 asistentes. Se publicó el libro conmemorativo "30 Años de Fe en la Frontera".', event_date:'2008-08-15', category:'Aniversario' },
]
export const DEMO_TESTIMONIES = [
  { id:1, church_id:1, event_id:1, author_name:'Descendiente de la Familia Ramírez', content:'Mi bisabuelo fue uno de los 45 fundadores. Recuerdo los relatos sobre cómo llegaron a pie desde el rancho para ese primer culto histórico.', year:2024 },
  { id:2, church_id:1, event_id:2, author_name:'María Elena Gutiérrez', content:'Mi madre me contó que fue en esa campaña donde encontró la fe. Tenemos el programa original guardado como reliquia.', year:2023 },
  { id:3, church_id:3, event_id:3, author_name:'Pastor Roberto Orozco', content:'Ser parte de esa generación que vio el avivamiento en la capital fue transformador. Muchos lo consideran el mayor movimiento espiritual del siglo XX en México.', year:2022 },
  { id:4, church_id:4, event_id:7, author_name:'Dr. Carlos Mendoza — Historiador', content:'Este archivo es un tesoro nacional. Las fotografías del siglo XIX de comunidades evangélicas en Oaxaca son únicas en América Latina.', year:2024 },
]
